import os
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from datetime import datetime

def generate_sustainability_pdf(output_path, data):
    """
    Generates a professional sustainability report PDF.
    data: {
        'title': str,
        'summary': dict,
        'resources': list of dicts
    }
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()

    # Custom Styles
    title_style = ParagraphStyle(
        'MainTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#16a34a"), # Eco Green
        spaceAfter=12
    )
    
    subtitle_style = ParagraphStyle(
        'SubTitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.gray,
        spaceAfter=30
    )

    # Title & Metadata
    elements.append(Paragraph("Sustainability Audit Report", title_style))
    elements.append(Paragraph(f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} UTC", subtitle_style))
    elements.append(Spacer(1, 12))

    # Executive Summary Section
    elements.append(Paragraph("Executive Summary", styles['Heading2']))
    summary_data = [
        ["Metric", "Value"],
        ["Total Resources Monitored", str(data['summary'].get('total_resources', 0))],
        ["Total Monthly Carbon (Est.)", f"{data['summary'].get('total_carbon', 0):.2f} kg CO2e"],
        ["Average Efficiency", f"{data['summary'].get('avg_efficiency', 0):.1f}%"],
    ]
    t = Table(summary_data, colWidths=[200, 100])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f0fdf4")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#16a34a")),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.whitesmoke)
    ]))
    elements.append(t)
    elements.append(Spacer(1, 30))

    # Resource Detail Table
    elements.append(Paragraph("Resource Sustainability Breakdown", styles['Heading2']))
    resource_data = [["Resource Name", "Type", "Carbon (kg/hr)", "Status"]]
    for res in data.get('resources', []):
        resource_data.append([
            res.get('name', 'Unknown'),
            res.get('type', 'Unknown'),
            f"{res.get('carbon_emissions', 0):.4f}",
            res.get('status', 'Unknown')
        ])
    
    rt = Table(resource_data, colWidths=[150, 100, 100, 100])
    rt.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('FONTSIZE', (0, 0), (-1, -1), 9)
    ]))
    elements.append(rt)

    # Footer
    elements.append(Spacer(1, 40))
    elements.append(Paragraph("This document is a verified sustainability artifact generated by the SaveEnergy GreenOps platform.", styles['Italic']))

    doc.build(elements)
    return output_path
